trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  GOBIN:  '$(system.defaultWorkingDirectory)/bin' # Go binaries path

steps:
- task: GoTool@0
  displayName: 'Set up the Go workspace'
  inputs:
    version: 1.25.6
    goPath: $(System.DefaultWorkingDirectory)/go
- script: |
    ls -la $(system.defaultWorkingDirectory)
  displayName: 'List files in the working directory'

