networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}
  minio_data: {}
  postgresql_data:
    driver: local
  pgadmin_working_dir:
    driver: local
  pgadmin_config_dir:
    driver: local

services:
  app:
    labels:
      app: munchin
      env: dev
    build: .
    env_file: .munchin.env
    container_name: app
    depends_on:
      - postgres
    ports:
      - "1337:1337" # HOST_PORT:CONTAINER_PORT
      - "8080:8080"
    networks:
      - monitoring
    develop:
      watch:
        - action: sync
          path: pkg
          target: pkg
          ignore:
            - alertmanager
            - loki
            - grafana
            - example.log
        - action: rebuild
          path: go.mod


  postgres:
     image: postgres:17.4-alpine
     container_name: postgres
     volumes:
       - postgresql_data:/var/lib/postgresql/data
     env_file:
       - .env    
     environment:
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     ports:
       - "5432:5432" # HOST_PORT:CONTAINER_PORT
     networks:
       - monitoring

  metabase:
    image: metabase/metabase:latest # To download the latest image
    container_name: metabase
    depends_on:
      - postgres
    ports:
      - "5434:3000" # HOST_PORT:CONTAINER_PORT

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --log.level=debug
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
       - ./configs/alertmanager:/etc/alertmanager
    command:
       - '--config.file=/etc/alertmanager/config.yml'
       - '--storage.path=/alertmanager'
    ports:
       - "9093:9093"
    networks:
       - monitoring
    restart: unless-stopped 

  minio:
    image: minio/minio
    container_name: minio
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/mimir && minio server --quiet /data"]
    ports:
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=mimir
      - MINIO_ROOT_PASSWORD=supersecret
    volumes:
      - minio_data:/data

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./configs/loki.yml:/etc/loki/loki.yml
    ports:
      - "3100:3100"
    networks:
      - monitoring
    restart: unless-stopped

  tempo:
    image: grafana/tempo
    container_name: tempo
    command: -config.file=/etc/tempo/tempo.yml
    volumes:
      - ./configs/tempo.yml:/etc/tempo/tempo.yml
    ports:
      - "3200:3200"   # Tempo HTTP
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks:
      - monitoring
    restart: unless-stopped

  alloy:
    image: grafana/alloy:v1.12.1
    container_name: alloy
    networks:
      - monitoring
    volumes:
      - ./configs/config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345"
      - "4319:4319"
      - "4317:4317"   # OTLP gRPC
    depends_on:
      - tempo


  # promtail:
  #   image: grafana/promtail:3.2.1
  #   container_name: promtail
  #   command: -config.file=/etc/promtail/promtail.yml
  #   volumes:
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./promtail.yml:/etc/promtail/promtail.yml
  #   networks:
  #     - monitoring
  #   depends_on:
  #     - loki
  #   restart: unless-stopped
