networks:
  monitoring: {}

volumes:
  prometheus_data:
  prometheus_config:
  grafana_data:
  grafana_provisioning:
  alertmanager_config:
  loki_config:
  tempo_config:
  tempo_data:
  alloy_config:

services:
  # -------- PROMETHEUS CONFIG INIT --------
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_config:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    expose:
      - 9090
    networks: [monitoring]

  # -------- GRAFANA --------
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_FEATURE_TOGGLES_ENABLE: "traceqlEditor metricsSummary"
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3000:3000"
    networks: [monitoring]

  # -------- ALERTMANAGER --------
  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - alertmanager_config:/etc/alertmanager
      - ./configs/alertmanager.yml:/etc/alertmanager/config.yml:ro
    expose:
      - 9093
    networks: [monitoring]

  # -------- LOKI --------
  loki:
    image: grafana/loki:2.9.4
    volumes:
      - loki_config:/etc/loki
      - ./configs/loki.yml:/etc/loki/loki.yml:ro
    expose:
      - 3100
    networks: [monitoring]

  # -------- TEMPO --------
  tempo:
    image: grafana/tempo:latest
    volumes:
      - tempo_config:/etc/tempo
      - ./configs/tempo.yml:/etc/tempo/tempo.yml:ro
      - tempo_data:/var/tempo
    command: ["-config.file=/etc/tempo/tempo.yml"]
    expose:
      - 3200
    networks: [monitoring]

  # -------- ALLOY --------
  alloy:
    image: grafana/alloy:latest
    depends_on: [tempo]
    volumes:
      - alloy_config:/etc/alloy
      - ./configs/alloy.hcl:/etc/alloy/alloy.hcl:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - run
      - /etc/alloy/alloy.hcl
    expose:
      - 4317
      - 4318
      - 12345
    networks: [monitoring]
