stream_over_http_enabled: true
auth_enabled: false
querier:
  query_live_store: true

server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"

metrics_generator:
  ring:
    kvstore:
      store: inmemory

  processor:
    service_graphs: {}
    span_metrics: {}

  storage:
    path: /var/tempo/generator

overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
        - local-blocks

storage:
  trace:
    backend: local # backend configuration to use
    local:
      path: /var/tempo/blocks
