stream_over_http_enabled: true
auth_enabled: false

server:
  http_listen_port: 3200
  log_level: debug

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"

storage:
  trace:
    backend: local # backend configuration to use
    local:
      path: /var/tempo/blocks
