// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Works as a probe like healhtz check",
                "tags": [
                    "healt"
                ],
                "summary": "Check health of the service",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/lobby": {
            "get": {
                "description": "List all game lobbies based",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lobby"
                ],
                "summary": "List Lobbies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/lobbies.LobbyListResponse"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "lobbies.LobbyListItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "playerCount": {
                    "type": "integer"
                },
                "state": {
                    "$ref": "#/definitions/lobbies.LobbyState"
                }
            }
        },
        "lobbies.LobbyListResponse": {
            "type": "object",
            "properties": {
                "hasMore": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lobbies.LobbyListItem"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "lobbies.LobbyState": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "FULL",
                "IN_GAME"
            ],
            "x-enum-varnames": [
                "StateAvailable",
                "StateFull",
                "StateInGame"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Munchin API",
	Description:      "This is the API for Munchin game backend",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
