// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate a user using username and password and return a JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate a user",
                "parameters": [
                    {
                        "description": "Authentication credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Authentication successful",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid credentials or malformed request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a new user with username and password and return a JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Registration successful",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or user already exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Works as a probe like healhtz check",
                "tags": [
                    "health"
                ],
                "summary": "Check health of the service",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/lobby": {
            "get": {
                "description": "Retrieve a paginated list of lobbies for the lobby selection scene (Game Endpoint).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lobby"
                ],
                "summary": "List lobbies",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Maximum number of items to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of lobbies",
                        "schema": {
                            "$ref": "#/definitions/lobbies.LobbyListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new game lobby and initialize its game room for the authenticated player.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lobby"
                ],
                "summary": "Create a new lobby",
                "responses": {
                    "201": {
                        "description": "Lobby successfully created",
                        "schema": {
                            "$ref": "#/definitions/lobbies.LobbyCreationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or unknown lobby",
                        "schema": {
                            "$ref": "#/definitions/lobbies.LobbyCreationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/lobby/model": {
            "get": {
                "description": "Retrieve all lobbies without pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lobby"
                ],
                "summary": "Get all lobbies",
                "responses": {
                    "200": {
                        "description": "List of lobbies",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/lobbies.LobbyListItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/lobby/{id}/join": {
            "post": {
                "description": "Join an existing game lobby as the authenticated player.",
                "tags": [
                    "game"
                ],
                "summary": "Join a game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lobby ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully joined the game",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Missing lobby ID or invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Lobby not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/lobby/{id}/start": {
            "post": {
                "description": "Start the game associated with a lobby.",
                "tags": [
                    "game"
                ],
                "summary": "Start a game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lobby ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Game started",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Missing lobby ID or invalid lobby",
                        "schema": {
                            "$ref": "#/definitions/lobbies.LobbyCreationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.AuthRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "lobbies.LobbyCreationResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "lobby_id": {
                    "type": "string"
                }
            }
        },
        "lobbies.LobbyListItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "playerCount": {
                    "type": "integer"
                },
                "state": {
                    "$ref": "#/definitions/lobbies.LobbyState"
                }
            }
        },
        "lobbies.LobbyListResponse": {
            "type": "object",
            "properties": {
                "hasMore": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lobbies.LobbyListItem"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "lobbies.LobbyState": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "FULL",
                "IN_GAME"
            ],
            "x-enum-varnames": [
                "StateAvailable",
                "StateFull",
                "StateInGame"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:1337",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Munchin API",
	Description:      "This is the API for Munchin game backend",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
